src/Cielo.Web.Sample/Controllers/CieloBuyPageCartController.cs
using System;
using System.Globalization;
using System.Web.Mvc;
using Cielo.Configuration;
using Cielo.Enums;
using Cielo.Requests;
using Cielo.Requests.Entities;
using Cielo.Responses;

namespace Cielo.Web.Sample.Controllers
{
    public class CieloBuyPageCartController : Controller
    {
        private CieloService _cieloService;
        private string _randomOrderId;
        private CustomCieloConfiguration _configuration;

        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            _cieloService = new CieloService();
            _randomOrderId = new Random().Next(11111, 9999999).ToString(CultureInfo.InvariantCulture);
            _configuration = new CustomCieloConfiguration
            {
                CurrencyId = "986",
                CustomerId = "1001734898",
                CustomerKey = "e84827130b9837473681c2787007da5914d6359947015a5cdb2b8843db0fa832",
                Language = Language.Portuguese,
                ReturnUrl = "http://localhost:5654/CieloBuyPageCart/Callback"
            };

            base.OnActionExecuting(filterContext);
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Checkout()
        {
            var order = new Order(_randomOrderId, 4700.00m, DateTime.Now, "Goku e GokuSSJ");
            var paymentMethod = new PaymentMethod(CreditCard.MasterCard, PurchaseType.Credit);
            var options = new CreateTransactionOptions(AuthorizationType.AuthorizeSkippingAuthentication, capture: true);
            var createTransactionRequest = new CreateTransactionRequest(order, paymentMethod, options, configuration: _configuration);
            CreateTransactionResponse response = _cieloService.CreateTransaction(createTransactionRequest);

            Session["tid"] = response.Tid;
            return Redirect(response.AuthenticationUrl);
        }

        public ActionResult Callback()
        {
            var checkTransactionRequest = new CheckTransactionRequest((string)Session["tid"], _configuration);
            CheckTransactionResponse response = _cieloService.CheckTransaction(checkTransactionRequest);
            ViewBag.Status = response.Status.ToString();

            return View();
        }
    }
}

src/Cielo.Web.Sample/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Cielo.Web.Sample.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

src/Cielo.Web.Sample/Controllers/LojaBuyPageCartController.cs
using System;
using System.Globalization;
using System.Web;
using System.Web.Mvc;
using System.Web.Util;
using Cielo.Configuration;
using Cielo.Enums;
using Cielo.Requests;
using Cielo.Requests.Entities;
using Cielo.Responses;
using Cielo.Responses.Exceptions;

namespace Cielo.Web.Sample.Controllers
{
    public class LojaBuyPageCartController : Controller
    {
        private CieloService _cieloService;
        private string _randomOrderId;
        private CustomCieloConfiguration _configuration;

        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            _cieloService = new CieloService();
            _randomOrderId = new Random().Next(11111, 9999999).ToString(CultureInfo.InvariantCulture);
            _configuration = new CustomCieloConfiguration
            {
                CurrencyId = "986",
                CustomerId = "1006993069",
                CustomerKey = "25fbb99741c739dd84d7b06ec78c9bac718838630f30b112d033ce2e621b34f3",
                Language = Language.Portuguese,
                ReturnUrl = "http://localhost:5654/LojaBuyPageCart/Callback"
            };

            base.OnActionExecuting(filterContext);
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Checkout()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Checkout(CheckoutViewModel creditCardValues)
        {
            var yearExpiration = Convert.ToInt16((string)creditCardValues.ExpirationYear);
            var monthExpiration = Convert.ToByte((string)creditCardValues.ExpirationMonth);

            var order = new Order(_randomOrderId, 4700.00m, DateTime.Now, "Goku e GokuSSJ");
            var paymentMethod = new PaymentMethod(CreditCard.MasterCard, PurchaseType.Credit);
            var options = new CreateTransactionOptions(AuthorizationType.AuthorizeSkippingAuthentication, capture: true);
            var creditCardData = new CreditCardData(creditCardValues.CreditCardNumber, new CreditCardExpiration(yearExpiration, monthExpiration), SecurityCodeIndicator.Sent, creditCardValues.SecurityCode);
            var createTransactionRequest = new CreateTransactionRequest(order, paymentMethod, options, creditCardData, _configuration);

            try
            {
                var response = _cieloService.CreateTransaction(createTransactionRequest);
                Session["tid"] = response.Tid;
                return Redirect("CheckStatus");
            }
            catch (ResponseException ex)
            {
                ViewBag.MessageError = ex.Message;
                return View(creditCardValues);
            }
        }

        public ActionResult CheckStatus()
        {
            var checkTransactionRequest = new CheckTransactionRequest((string)Session["tid"], _configuration);
            CheckTransactionResponse response = _cieloService.CheckTransaction(checkTransactionRequest);
            ViewBag.Status = response.Status.ToString();

            return View();
        }

        public class CheckoutViewModel
        {
            public string SecurityCode { get; set; }
            public string ExpirationYear { get; set; }
            public string ExpirationMonth { get; set; }
            public string CreditCardNumber { get; set; }
        }
    }
}

src/Cielo.Web.Sample/Views/CieloBuyPageCart/Callback.cshtml
@model dynamic
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <title>Shopping Cart</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
</head>
<body>
    <div class="container">
        <div class="page-header">
            <h1>Confirmation page <small>transaction completed</small></h1>
        </div>
        <h2>@ViewBag.Status</h2>

        <div class="row">
            <div class="span3">
                <a href="@Url.Action("Callback", "CieloBuyPageCart")" class="btn btn-primary" type="submit">
                    Refresh page
                </a>
            </div>
        </div>
    </div>
</body>
</html>

src/Cielo.Web.Sample/Views/CieloBuyPageCart/Index.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <title>Shopping Cart</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
</head>
<body>
    <div class="container">
        <br />
        <br />
        <h1>Shopping Cart</h1>
        <br />
        @Html.Partial("_FakeShoppingCart")

        @using (Html.BeginForm("Checkout", "CieloBuyPageCart", FormMethod.Post))
        {
            <div class="row">
                <div class="pull-right">
                    <button class="btn btn-primary" disabled="disabled">Continue shopping</button>
                    <button class="btn btn-primary" type="submit">Checkout</button>
                </div>
            </div>
        }
    </div>

</body>
</html>

src/Cielo.Web.Sample/Views/Home/Index.cshtml
@model dynamic
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <title>Cielo Samples</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
</head>
<body>
    <div class="container">
        <div class="page-header">
            <h1>Yay, we have 2 modes of integration</h1>
        </div>
        <div class="row">
            <div class="span3">
                <a class="btn btn-primary" href="@Url.Action("Index", "CieloBuyPageCart")">CieloBuyPage</a>
                <a class="btn btn-primary" href="@Url.Action("Index", "LojaBuyPageCart")">LojaBuyPage</a>
            </div>
        </div>
    </div>
</body>
</html>

src/Cielo.Web.Sample/Views/LojaBuyPageCart/CheckStatus.cshtml
@model dynamic
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <title>Shopping Cart</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
</head>
<body>
    <div class="container">
        <div class="page-header">
            <h1>Confirmation page <small>transaction completed</small></h1>
        </div>
        <h2>@ViewBag.Status</h2>

        <div class="row">
            <div class="span3">
                <a href="@Url.Action("CheckStatus", "LojaBuyPageCart")" class="btn btn-primary" type="submit">
                    Refresh page
                </a>
            </div>
        </div>
    </div>
</body>
</html>

src/Cielo.Web.Sample/Views/LojaBuyPageCart/Checkout.cshtml
@model dynamic
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <title>Shopping Cart</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
</head>
<body>
    <div class="container">
        @using (Html.BeginForm())
        {
            <fieldset class="form-horizontal">
                <legend>Checkout</legend>

                @if (ViewBag.MessageError != null)
                { 
                    <div class="alert alert-error">
                        @ViewBag.MessageError
                    </div>
                }

                <div class="control-group">
                    <label for="creditcard" class="control-label">Credit card number</label>
                    <div class="controls">
                        <input id="creditcard" type="text" name="CreditCardNumber" maxlength="16" value="6362970000457013" />
                    </div>
                </div>

                <div class="control-group">
                    <label for="expiration-year" class="control-label">Expiration</label>
                    <div class="controls">
                        <input id="expiration-year" class="span1" type="text" name="ExpirationYear" maxlength="4" value="2018" />
                        <input id="expiration-month" class="span1" type="text" name="ExpirationMonth" maxlength="2" value="05" />
                    </div>
                </div>

                <div class="control-group">
                    <label for="securitycode" class="control-label">Security code</label>
                    <div class="controls">
                        <input id="securitycode" class="span1" type="text" name="SecurityCode" maxlength="4" value="123" />
                    </div>
                </div>

                <div class="form-actions">
                    <button type="submit" class="btn btn-success">
                        Checkout</button>
                    <button class="btn btn-danger" disabled="disabled">Cancel</button>
                </div>

            </fieldset>
        }
    </div>
</body>
</html>

src/Cielo.Web.Sample/Views/LojaBuyPageCart/Index.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <title>Shopping Cart</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
</head>
<body>
    <div class="container">
        <br />
        <br />
        <h1>Shopping Cart</h1>
        <br />
        @Html.Partial("_FakeShoppingCart")

        @using (Html.BeginForm("Checkout", "LojaBuyPageCart", FormMethod.Get))
        {
            <div class="row">
                <div class="pull-right">
                    <button class="btn btn-primary" disabled="disabled">Continue shopping</button>
                    <button class="btn btn-primary" type="submit">Checkout</button>
                </div>
            </div>
        }
    </div>

</body>
</html>

src/Cielo.Web.Sample/Views/Shared/_FakeShoppingCart.cshtml
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Remove</th>
            <th>Image</th>
            <th>Product Name</th>
            <th>Model</th>
            <th>Quantity</th>
            <th>Unit Price</th>
            <th>Total</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td class="">
                <input type="checkbox" value="option1" disabled="disabled"></td>
            <td class="muted"><a href="#">
                <img src="~/Content/Images/GokuProduct.jpg" width="80" height="80">
            </a></td>
            <td>Goku</td>
            <td>Product 18</td>
            <td>
                <input type="text" placeholder="1" class="input-mini" disabled="disabled"></td>
            <td>$2,350.00</td>
            <td>$2,350.00</td>
        </tr>
        <tr>
            <td class="">
                <input type="checkbox" value="option1" disabled="disabled"></td>
            <td class="muted"><a href="#">
                <img src="~/Content/Images/GokuProductSSJ.jpg" width="80" height="80">
            </a></td>
            <td>Goku SSJ</td>
            <td>Product 18</td>
            <td>
                <input type="text" placeholder="1" class="input-mini" disabled="disabled"></td>
            <td>$2,350.00</td>
            <td>$2,350.00</td>
        </tr>
        <tr>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td><strong>$4,700.00</strong></td>
        </tr>
    </tbody>
</table>